### PR TITLE
Add a markdown template for our portfolio

### PR DESCRIPTION
**Pull request by Suavesito-Olimpiada**
Here I add the markdown template for our portfolio, this includes show-off of the sections with my info.

### CODE REVIEW

**Review by Reemeela2121 — COMMENTED** [review]
This looks good!  is the image.jpg file an actual image or a placeholder of where we can put pictures?

**Comment by Suavesito-Olimpiada** [comment]
> is the image.jpg file an actual image or a placeholder of where we can put pictures?

It is a place-holder for images, the images must be inside `app/static/img` or be links to some other place in the internet.

**Review by Reemeela2121 — APPROVED** [review]
I think this looks good so far! I'm curious to see how we can use locomotive scroll with pando-rendered html files.

**Comment by Suavesito-Olimpiada** [comment]
The idea is that If all our md portfolos "looks" the same, I can change the html to make it look better very easily. Like to have and initial steo to work with the teplate and experiment. :smiley:

**Review by nvenkate-cyber — COMMENTED** [review]
Looks good to me!

**Pull request merged**
